### ISSUE TITLE
Set Dressing Pass 1

### ISSUE THREAD

**Issue by HschwandtHCC** [GAME-2334/vrgame#38]
Please set art assets from the marketplace in the scene accordingly. Keep in mind structure and delight as you build up our scene from the greybox outline.

**Comment by SBM382** [comment]
Bedroom
![Bedroom](https://user-images.githubusercontent.com/70292179/219828939-d4f2ead8-4124-455f-9c34-07cb4b090703.png)
![Bedroom_2](https://user-images.githubusercontent.com/70292179/219828942-779b8a47-bb5b-44ca-ab3d-99937e893ea6.png)
1st_Hallway
![1st_Hallway](https://user-images.githubusercontent.com/70292179/219828955-c8876180-9ad8-4a51-a5f9-7becaa030527.png)
Hallway
![Hallway_1](https://user-images.githubusercontent.com/70292179/219828972-ee3a7cb7-40d0-435a-b57a-8c96d4557173.png)
![Hallway_2](https://user-images.githubusercontent.com/70292179/219828973-6f25b317-3316-49bc-95ae-6f2df2f142c0.png)
Room 121 
![Room121_1](https://user-images.githubusercontent.com/70292179/219828984-e7596379-4137-491e-ab27-4890b22cc559.png)
![Room121_2](https://user-images.githubusercontent.com/70292179/219828985-68980d7e-e61c-40b4-9d9b-3010dc05cf94.png)
Restroom
![Restroom](https://user-images.githubusercontent.com/70292179/219829003-b6058674-2430-4ba4-a209-1c222c474e7b.png)
HallWay 2nd floor
![Hallway_1](https://user-images.githubusercontent.com/70292179/219829157-1937fe4f-6274-47a1-a24d-6d0849d1a668.png)
![Hallway_2](https://user-images.githubusercontent.com/70292179/219829158-8401fb6f-9139-4a98-b37c-0fee91a72669.png)
Cafe
![Cafe_5](https://user-images.githubusercontent.com/70292179/219829013-36c40895-3a34-4d17-b7e0-1ec356e38b1f.png)
![Cafe_1](https://user-images.githubusercontent.com/70292179/219829015-0f1b2e94-d319-4bf5-99e7-a9f7c90b1c11.png)
![Cafe_2](https://user-images.githubusercontent.com/70292179/219829017-3cbf6232-f691-421a-8ab5-d59e32a562c4.png)
![Cafe_4](https://user-images.githubusercontent.com/70292179/219829018-dd3f8b42-e7dd-49c8-9a62-16570b3fa77b.png)
Hub
![Hub_4](https://user-images.githubusercontent.com/70292179/219829026-3b8a7820-be50-4a08-ae2c-36e1d9dd1211.png)
![Hub_1](https://user-images.githubusercontent.com/70292179/219829027-f5c29357-0ff8-40db-8612-81bc3a8f52b9.png)
![Hub_2](https://user-images.githubusercontent.com/70292179/219829029-930e6c37-25f5-40a3-8d54-81d65047d034.png)
![Hub_3](https://user-images.githubusercontent.com/70292179/219829030-78fa261f-b7f1-44f6-a905-b6011f49387a.png)
Second Hub
![Hub2_3](https://user-images.githubusercontent.com/70292179/219829051-7a8d4014-56fe-47b1-acc5-690a02539385.png)
![Hub2_1](https://user-images.githubusercontent.com/70292179/219829052-8a92afd6-d2ed-47bb-bb5c-88f4a44c12b5.png)
![Hub2_2](https://user-images.githubusercontent.com/70292179/219829054-4ba0f3b8-4c1f-4e20-8d9a-23b8967d77c1.png)
Lab 1
![Lab1_2](https://user-images.githubusercontent.com/70292179/219829062-5c71076d-b0eb-4ad8-b71d-c442957583d3.png)
![Lab1_1](https://user-images.githubusercontent.com/70292179/219829064-88187f0d-0353-441e-8a41-7abf4561bc42.png)
Lab 2
![Lab2_3](https://user-images.githubusercontent.com/70292179/219829069-4a30365e-6e61-4142-b3ab-2ed91fc96c1c.png)
![Lab2_1](https://user-images.githubusercontent.com/70292179/219829071-d62034ad-21b7-41fa-8cae-0bf1788bfa7d.png)
![Lab2_2](https://user-images.githubusercontent.com/70292179/219829072-8d58dd2d-1bab-49b0-931c-9333a284fb18.png)
Power Station
![PowerS_1](https://user-images.githubusercontent.com/70292179/219829082-2a57e7dc-e76e-47ef-bd1d-7da053a34345.png)
![PowerS_2](https://user-images.githubusercontent.com/70292179/219829083-3a83cc05-7cbe-46dc-bb26-78dff0e1fa8d.png)
![PowerS_3](https://user-images.githubusercontent.com/70292179/219829084-437e063d-6f98-41af-ab18-2debd9c1cd1a.png)
Security room
![Security_2](https://user-images.githubusercontent.com/70292179/219829111-05de4938-88f8-44d9-8046-f6f224b61a74.png)
![Security_1](https://user-images.githubusercontent.com/70292179/219829112-917f7f9d-5ac7-4dac-bbf6-5b692956a692.png)
Scape Pod room
![ScapePod_1](https://user-images.githubusercontent.com/70292179/219829119-8e4ed28a-886a-4386-b810-faa3462171c7.png)
![ScapePod_2](https://user-images.githubusercontent.com/70292179/219829120-967f0b92-e003-4831-a0b1-a00d22f02e42.png)
