### ISSUE TITLE
3D Assets/Marketplace downloads

### ISSUE THREAD

**Issue by HschwandtHCC** [GAME-2334/vrgame#4]
Please download the assets assigned by Chris and examine them for usefulness in our specific project. Take note of any items that will add to the "Screenshot worthy" standard we are after for the worldbuilding!

**Comment by SBM382** [comment]
These assets packs that I could download 

•	Sci-Fi Props Vol1
•	Modular Sci-Fi Season 1 starter Bundle 
•	Modular Sci-Fi Season 2 starter Bundle 
•	4 in 1 Modular Research Facility

**Comment by professaurChris** [comment]
@SBM382 I don't see it on the repo. Please make sure it's on the repo/design branch before we consider this task completed. 


Did you want these? 

polar sci fi facility
science laboratory
spaceship interior environment set
zero gravity ultimate sci-fi collection

**Comment by SBM382** [comment]
It was like a question to confirm if those assets were fine to use.  And I cannot marked it as close issue.

**Comment by professaurChris** [comment]
Those assets should be fine to use. However, until it's on the repo, cannot consider this issue closed.

**Comment by SBM382** [comment]
Assets are already on the repo
