### ISSUE TITLE
Map Sketch

### ISSUE THREAD

**Issue by HschwandtHCC** [GAME-2334/vrgame#5]
Please sketch a digital "papermap" in photoshop for our level design. Create it quickly and efficiently so that we can make swift edits and get it approved and realized as a greybox asap. Implement a legend that is clear and be thinking of level "flow" as well as scale, and how long it will take for the player to go through the whole experience.

**Comment by NekotTheBrave** [comment]
![Image](https://user-images.githubusercontent.com/67830152/215650853-53deb67c-b456-4d04-ac6a-3cc19f12c643.png)
Latest 2D Map Design

**Comment by professaurChris** [comment]
This still needs work. Going over our last discussion, looking for an update where you don't return to the lobby or vicinity of the lobby more than two times. Three is enough and fourth should break away from the hub. Changes can reflect on gameplay experience, aesthetics, and/or sound. Base on topic of 'beats.' Also refer to hub to linear to hub, or hub to linear to another linear level providing a little more direction with the user experience.

**Comment by professaurChris** [comment]
Please submit your latest sketches on here.

**Comment by NekotTheBrave** [comment]
![Image](https://user-images.githubusercontent.com/67830152/217105457-8e95ad18-fd75-4c55-b0e8-8f0427497961.png)
Latest Level Design

**Comment by NekotTheBrave** [comment]
Updated Document to indicate Level 1 and Level 2

![Image](https://user-images.githubusercontent.com/67830152/217106369-e7b2a09b-8625-4316-a430-f75040c2a535.png)
