### ISSUE TITLE
Character Concept Art

### ISSUE THREAD

**Issue by Adicus-Alexander** [GAME-2334/vrgame#7]
Create Concept art for the player character, Connie Williams. 

Connie is a maintenance worker on Moonbase WL Sector C121. As a maintenance worker her clothes, hair, and gear should be practical for her daily duties. This includes cleaning, routine mechanical maintenance, and routine refueling. Please reference modern and Science fiction space suits and uniform designs. 

Please include 2-3 iterations of the character design. Each iteration should include at least a full body in a front-facing view and one other angle. At least one should include color.

**Comment by spiffyspades** [comment]
![Sbeidy_Connie_spacesuitconcepts](https://user-images.githubusercontent.com/112118309/215649986-82815169-b1b9-4614-b63e-486e608fc1f4.png)

**Comment by Adicus-Alexander** [comment]
Please list the types of materials used for the final design

**Comment by spiffyspades** [comment]
![Connie_spacesuitconcepts_materiallabels](https://user-images.githubusercontent.com/112118309/217050088-bc839669-c2de-4057-bb8f-dbcd38845a54.png)
