### ISSUE TITLE
Elevator

### ISSUE THREAD

**Issue by aeonic-dev** [GAME-2334/vrgame#73]
Elevator prefab should exist on all floors simultaneously. Normal door to enter it, either the door blueprint or a copy of it. A few buttons for floors within the elevator, for whichever ones are accessible. When one is pressed, the player is teleported to the given floor after a short delay. Eventually during this delay we'll try to make the screen shake and play a sound.

Alternatively you can have the elevator physically move with the player, but then calling and moving it will just be a more complex implementation.

**Comment by NekotTheBrave** [comment]
https://www.screencast.com/t/kQ63EdadddOt
